# Generated by Django 3.2.4 on 2022-02-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentThemePosters',
            new_name='RecentThemeMovies',
        ),
    ]
