# Generated by Django 3.2.4 on 2022-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleEarthModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=100)),
                ('shortDescription', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['moduleName'],
            },
        ),
    ]
