# Generated by Django 3.2.4 on 2021-06-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20210605_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(help_text='mandatory', max_length=100),
        ),
    ]
