# Generated by Django 3.2.4 on 2022-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20220218_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='lenght',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='time_period',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(help_text='Name of Movie/Documentary/...', max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year the Movie released', null=True),
        ),
    ]
