# Generated by Django 3.2.4 on 2021-06-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_alter_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
