# Generated by Django 3.2.4 on 2021-06-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('lenght', models.CharField(max_length=10)),
                ('time_period', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
