# Generated by Django 3.2.4 on 2022-02-22 06:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='country')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='director')),
            ],
            options={
                'ordering': ['director'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='language')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.URLField(default='https://d32qys9a6wm9no.cloudfront.net/images/movies/poster/500x735.png')),
                ('year', models.IntegerField()),
                ('length', models.CharField(blank=True, help_text='Use HH:MM:SS format', max_length=10, null=True)),
                ('seasons', models.CharField(blank=True, max_length=150, null=True)),
                ('episodes', models.CharField(blank=True, help_text='In case the show only has one season', max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('category', models.ManyToManyField(to='movies.Category')),
                ('country', models.ManyToManyField(to='movies.Country')),
                ('director', models.ManyToManyField(to='movies.Director')),
                ('language', models.ManyToManyField(to='movies.Language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='theme')),
            ],
            options={
                'ordering': ['theme'],
            },
        ),
        migrations.CreateModel(
            name='MovieTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movies')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.theme')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='themes',
            field=models.ManyToManyField(to='movies.Theme'),
        ),
    ]
