# Generated by Django 3.2.4 on 2022-02-18 15:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='country')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='director')),
            ],
            options={
                'ordering': ['director'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='language')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='theme')),
            ],
            options={
                'ordering': ['theme'],
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='theme',
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='language',
        ),
        migrations.AlterField(
            model_name='movies',
            name='lenght',
            field=models.CharField(help_text='Use HH:MM:SS format', max_length=10),
        ),
        migrations.AlterField(
            model_name='movies',
            name='time_period',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='MovieTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movies')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.theme')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ManyToManyField(to='movies.Category'),
        ),
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.ManyToManyField(to='movies.Country'),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ManyToManyField(to='movies.Director'),
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.ManyToManyField(to='movies.Language'),
        ),
    ]
