# Generated by Django 3.2.4 on 2021-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'United States of America')], max_length=100),
        ),
    ]
