# Generated by Django 3.2.4 on 2022-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.URLField(default='https://d32qys9a6wm9no.cloudfront.net/images/movies/poster/500x735.png'),
        ),
    ]
