# Generated by Django 3.2.4 on 2021-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'United States of America'), ('Afghanistan', 'Afghanistan'), ('Angola', 'Angola'), ('Albania', 'Albania'), ('UAE', 'United Arab Emirates'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia')], max_length=100),
        ),
    ]
