# Generated by Django 3.2.4 on 2021-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_category_country_language_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ManyToManyField(to='movies.Category'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='country',
        ),
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.ManyToManyField(to='movies.Country'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='language',
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.ManyToManyField(to='movies.Language'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='theme',
        ),
        migrations.AddField(
            model_name='movies',
            name='theme',
            field=models.ManyToManyField(to='movies.Theme'),
        ),
    ]
