# Generated by Django 3.2.4 on 2021-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210615_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='accuracy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
