# Generated by Django 3.2.4 on 2021-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210618_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('time_period', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
