# Generated by Django 3.2.4 on 2021-06-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movies_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
