# Generated by Django 3.2.4 on 2021-06-23 05:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(default='default_director', editable=False, populate_from='director')),
            ],
            options={
                'ordering': ['director'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language']},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['theme']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_category', editable=False, populate_from='category'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_country', editable=False, populate_from='country'),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_lang', editable=False, populate_from='language'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_movie', editable=False, populate_from='title'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='time_period',
        ),
        migrations.AddField(
            model_name='movies',
            name='time_period',
            field=models.ManyToManyField(help_text='If choosing Transitioning also choose from which period to which period', to='movies.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_theme', editable=False, populate_from='theme'),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_time_period', editable=False, populate_from='time_period'),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ManyToManyField(to='movies.Director'),
        ),
    ]
