# Generated by Django 3.2.4 on 2021-06-23 06:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20210623_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_category', editable=False, max_length=100, populate_from='category'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_country', editable=False, max_length=100, populate_from='country'),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_director', editable=False, max_length=100, populate_from='director'),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_lang', editable=False, max_length=100, populate_from='language'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_movie', editable=False, max_length=100, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_theme', editable=False, max_length=100, populate_from='theme'),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_time_period', editable=False, max_length=100, populate_from='time_period'),
        ),
    ]
