# Generated by Django 3.2.4 on 2021-06-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20210625_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, height_field=300, max_length=200, upload_to='posters/', width_field=200),
        ),
    ]
