# Generated by Django 3.2.4 on 2021-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_movies_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='accuracy',
            new_name='para1',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='remarks',
            new_name='para2',
        ),
        migrations.AddField(
            model_name='movies',
            name='para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='para5',
            field=models.TextField(blank=True),
        ),
    ]
